#!/usr/bin/env bash

export ANT_OPTS="-Xss8M -Xmx4000M"

if hash silver 2>/dev/null; then
  # If 'silver' is in $PATH, this was run from the command line, presumably.
  SV="silver"
  SVTHEN="true"
  SVARGS="-I ../grammars"
else
  echo "Can't find silver to invoke"
  exit 1
fi

# basic sanity check
if [[ ! -d "../grammars/edu.umn.cs.melt.ableC" ]]; then
  echo "Can't find ableC grammar"
  exit 1
fi


$SV $SVARGS $@ -o ableC.jar edu:umn:cs:melt:ableC:testing && $SVTHEN || exit 1


