#!/bin/bash


FILES=`find . -name "*.errs"`

if [ "$1" == "" ]; then
  # strip off the file, line, column, and just print what errors appeared, somewhere
  grep -v "Error at line\|CPP call\|^ " $FILES | cut -d: -f5- | sort | uniq
else
  grep "$1" $FILES
fi

