#!/bin/bash

set -eu
shopt -s extglob

echo "Testing positive..."
java -Xss8M -jar ableC.jar tests/**/positive/!(*.pp_out).c | tee expected-results/positive.out

echo "Testing negative..."
java -Xss8M -jar ableC.jar tests/**/negative/!(*.pp_out).c  | tee expected-results/negative.out

echo "Testing neutral..."
java -Xss8M -jar ableC.jar tests/**/neutral/!(*.pp_out).c | tee expected-results/neutral.out

cd expected-results

set -ve

diff positive positive.out
diff negative negative.out
diff neutral neutral.out