#!/bin/bash

java -jar builtins.jar BuiltinsX86.def > ../../edu.umn.cs.melt.ableC/abstractsyntax/builtins/GeneratedIntrinsics.sv
java -jar builtins.jar Builtins.def > ../../edu.umn.cs.melt.ableC/abstractsyntax/builtins/GeneratedBuiltins.sv
